const keywordClassifications: { [key: string]: string } = {
  HAI: 'Code Delimiter',
  KTHXBYE: 'Code Delimiter',
  BUHBYE: 'Code Delimiter',
  'I HAS A': 'Variable Declaration',
  ITZ: 'Variable Assignment',
  R: 'Variable Assignment',
  VISIBLE: 'Output',
  GIMMEH: 'Input',
  'O RLY?': 'Conditional Statement',
  'YA RLY': 'Conditional Statement',
  MEBBE: 'Conditional Statement',
  'NO WAI': 'Conditional Statement',
  OIC: 'Conditional Statement',
  'WTF?': 'Switch Case',
  OMG: 'Switch Case',
  OMGWTF: 'Switch Case',
  'IM IN YR': 'Loop',
  UPPIN: 'Increment',
  NERFIN: 'Decrement',
  YR: 'Loop Delimiter',
  'IM OUTTA YR': 'Loop Delimiter',
  'FOUND YR': 'Loop Delimiter',
  TIL: 'Loop Delimiter',
  WILE: 'Loop Delimiter',
  'SUM OF': 'Arithmetic Operator',
  'DIFF OF': 'Arithmetic Operator',
  'PRODUKT OF': 'Arithmetic Operator',
  'QUOSHUNT OF': 'Arithmetic Operator',
  'MOD OF': 'Arithmetic Operator',
  'BIGGR OF': 'Logical Operator',
  'SMALLR OF': 'Logical Operator',
  'BOTH OF': 'Logical Operator',
  'EITHER OF': 'Logical Operator',
  'WON OF': 'Logical Operator',
  NOT: 'Logical Operator',
  'ANY OF': 'Logical Operator',
  'ALL OF': 'Logical Operator',
  'BOTH SAEM': 'Logical Operator',
  DIFFRINT: 'Logical Operator',
  SMOOSH: 'Logical Operator',
  MAEK: 'Logical Operator',
  AN: 'Logical Operator',
  'IS NOW A': 'Logical Operator',
  MKAY: 'Logical Operator',
  'IF U SAY SO': 'Exit',
  GTFO: 'Exit',
  'I IZ': 'Function Declaration',
  'HOW IZ I': 'Function Call'
}

export { keywordClassifications }
